config/routes.rb
Rails.application.routes.draw do
  resources :searches
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index
    parser = PhoneParser::Phonearena.new(params[:search][:phone_name])
    @dimensions = parser.data[:dimensions]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title SimplexTest
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    = csrf_meta_tags
  body
    .container.d-flex.h-100
      = yield

app/views/pages/home.slim
.row.justify-content-center.align-self-center.w-100
  = simple_form_for :search, url: searches_path, method: :get, remote: true, html: { class: 'form-inline preloader w-100' } do |f|
    .form-group.row.w-100
      .col-sm-8
        = f.label :phone_name, class: 'sr-only'
        = f.input_field :phone_name, class: 'form-control w-100', placeholder: 'Enter phone name'
      .col-sm-4
        = f.button :submit, 'Show dimensions'
  .col-sm-12.mt-sm-2
    p.dimensions

app/views/searches/index.js.erb
$('p.dimensions').text('Phone dimensions are: <%= @dimensions %>');